// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8KP5JZPN7bSFgUcfzeXFHJdqKP6cKczQ',
    appId: '1:210179324809:android:7383905c4dcea7e2633f58',
    messagingSenderId: '210179324809',
    projectId: 'inviti-community-app',
    storageBucket: 'inviti-community-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa26nJDgnm35_paPkJbW5wkKEk0cC856k',
    appId: '1:210179324809:ios:fdc098ba65b5bc77633f58',
    messagingSenderId: '210179324809',
    projectId: 'inviti-community-app',
    storageBucket: 'inviti-community-app.firebasestorage.app',
    iosBundleId: 'com.example.commaCommunityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvGuRii00RPVd5frH5BOCDqfrlRtYVMak',
    appId: '1:210179324809:web:25283396a6a4bf80633f58',
    messagingSenderId: '210179324809',
    projectId: 'inviti-community-app',
    authDomain: 'inviti-community-app.firebaseapp.com',
    storageBucket: 'inviti-community-app.firebasestorage.app',
    measurementId: 'G-HE2JHF7XVV',
  );
}
